# Dependencies
gems:
 - jekyll-coffeescript
 - jekyll-paginate
 - jekyll-feed
 - jekyll-github-metadata

keep_files: [".git"]
repository: coDual/codual.github.io

# Permalinks
permalink: pretty

# Setup
title: coDual
baseurl: /

authors:
  psi:
    name: Psi
    link: /psi
  m42:
    name: M42
    link: /m42

paginate: 5

defaults:
  - values:
      lang: es
      layout: post
      license: '<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA 4.0</a>'
      comments: true
