# Dependencies
gems:
 - jekyll-coffeescript
 - jekyll-paginate
 - jekyll-feed
 - jekyll-github-metadata
 - jemoji
 - jekyll-redirect-from

# Basic info
title: coDual
repository: coDual/codual.github.io
url: https://codual.github.io
baseurl: /

collections:
  log:
    layout: log
    output: true

# Appearance
defaults:
  - values:
      lang: es
      layout: post
      math: false
      code: false
      hidden: false
  - scope:
      path: ""
      type: log
    values:
      layout: log

permalink: pretty
kramdown:
  header_offset: 1
paginate: 20

# Authors
authors:
  psi:
    name: Pablo
    link: https://mx-psi.github.io
  m42:
    name: M42
    link: https://mroman42.github.io
