# Dependencies
gems:
 - jekyll-coffeescript
 - jekyll-paginate
 - jekyll-feed
 - jekyll-github-metadata
 - jemoji

# Basic info
title: coDual
repository: coDual/codual.github.io
url: https://codual.github.io
baseurl: /

# Appearance
defaults:
  - values:
      lang: es
      layout: post
      license: '<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA</a>'
      math: false
      code: false
      hidden: false
permalink: pretty
kramdown:
  header_offset: 1
paginate: 8

# Authors
authors:
  psi:
    name: Psi
    link: /psi
  m42:
    name: M42
    link: https://m42.github.io
