name: Links

on:
  repository_dispatch:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: "00 18 1 * *"

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check links
        uses: lycheeverse/lychee-action@v1.0.8
        with:
          # Exclude pages with aggressive rate-limiting
          # also exclude my username on Mastodon :)
          args: >
           --exclude ".*stackexchange.com.*" 
           --exclude ".*stackoverflow.com.*"
           --exclude ".*mathoverflow.com.*" 
           --exclude ".*archive.is.*"
           --exclude "mx_psi@mstdn.io"
           --github-token "${{secrets.GITHUB_TOKEN}}"
           --base-url "https://codual.github.io/" 
           --verbose --no-progress -- **/*.md **/*.html
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        
      - name: Create Issue From File
        uses: peter-evans/create-issue-from-file@v3
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue